baseURL = "http://neglostyti.com/"
languageCode = "en-us"
title = "neglostyti.com"

theme = "coder" # set the theme

[params] # theme parameters
    author = "Viktoras Makauskas" # author's name
    info = "things happen" # author's job title or info
    description = "Viktoras Makauskas' namespace" # site description
    keywords = "" # site keywords

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/viktorasm/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/viktorasm/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/viktoras-makauskas/"

[[menu.main]]
    name = "Projects"
    weight = 1
    url  = "/projects/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"